[[edge_functions]]
path = "/telegram"
function = "telegram"

[[edge_functions]]
path = "/watch"
function = "watch"

[[edge_functions]]
path = "/setDevelopmentVar"
function = "setDevelopmentVar"

[[edge_functions]]
path = "/oauthCallback"
function = "oauthCallback"
